/**
 * Game action types for Pinopoly v2
 * All mutations to game state happen through these actions
 */

import type {
  GameConfig,
  BotPersonality,
  Difficulty,
  TokenType,
  TradeOffer,
} from '../state/types';

// =============================================================================
// ACTION TYPE CONSTANTS
// =============================================================================

export const ActionTypes = {
  // Game Lifecycle
  INITIALIZE_GAME: 'INITIALIZE_GAME',
  START_GAME: 'START_GAME',
  PAUSE_GAME: 'PAUSE_GAME',
  RESUME_GAME: 'RESUME_GAME',
  END_GAME: 'END_GAME',

  // Lobby
  ADD_PLAYER: 'ADD_PLAYER',
  REMOVE_PLAYER: 'REMOVE_PLAYER',
  ADD_BOT: 'ADD_BOT',
  PLAYER_READY: 'PLAYER_READY',
  PLAYER_UNREADY: 'PLAYER_UNREADY',

  // Turn Actions
  ROLL_DICE: 'ROLL_DICE',
  END_TURN: 'END_TURN',

  // Property Actions
  BUY_PROPERTY: 'BUY_PROPERTY',
  DECLINE_PROPERTY: 'DECLINE_PROPERTY',
  BUILD_HOUSE: 'BUILD_HOUSE',
  SELL_HOUSE: 'SELL_HOUSE',
  MORTGAGE_PROPERTY: 'MORTGAGE_PROPERTY',
  UNMORTGAGE_PROPERTY: 'UNMORTGAGE_PROPERTY',

  // Jail Actions
  PAY_JAIL_FINE: 'PAY_JAIL_FINE',
  USE_JAIL_CARD: 'USE_JAIL_CARD',
  ROLL_FOR_DOUBLES: 'ROLL_FOR_DOUBLES',

  // Finance Actions
  TAKE_LOAN: 'TAKE_LOAN',
  REPAY_LOAN: 'REPAY_LOAN',
  CREATE_CD: 'CREATE_CD',
  WITHDRAW_CD: 'WITHDRAW_CD',
  OPEN_HELOC: 'OPEN_HELOC',
  DRAW_HELOC: 'DRAW_HELOC',
  REPAY_HELOC: 'REPAY_HELOC',

  // Trade Actions
  PROPOSE_TRADE: 'PROPOSE_TRADE',
  ACCEPT_TRADE: 'ACCEPT_TRADE',
  REJECT_TRADE: 'REJECT_TRADE',
  COUNTER_TRADE: 'COUNTER_TRADE',
  CANCEL_TRADE: 'CANCEL_TRADE',

  // Auction Actions
  START_AUCTION: 'START_AUCTION',
  PLACE_BID: 'PLACE_BID',
  PASS_AUCTION: 'PASS_AUCTION',

  // Card Actions
  DRAW_CARD: 'DRAW_CARD',
  EXECUTE_CARD: 'EXECUTE_CARD',

  // System Actions (generated by engine, not player-initiated)
  MOVE_PLAYER: 'MOVE_PLAYER',
  COLLECT_RENT: 'COLLECT_RENT',
  COLLECT_GO_SALARY: 'COLLECT_GO_SALARY',
  SEND_TO_JAIL: 'SEND_TO_JAIL',
  RELEASE_FROM_JAIL: 'RELEASE_FROM_JAIL',
  BANKRUPT_PLAYER: 'BANKRUPT_PLAYER',
  ECONOMY_TICK: 'ECONOMY_TICK',
  UPDATE_CREDIT_SCORE: 'UPDATE_CREDIT_SCORE',
  PROCESS_LOAN_PAYMENT: 'PROCESS_LOAN_PAYMENT',
  MATURE_CD: 'MATURE_CD',

  // Admin Actions
  ADMIN_ADJUST_MONEY: 'ADMIN_ADJUST_MONEY',
  ADMIN_MOVE_PLAYER: 'ADMIN_MOVE_PLAYER',
  ADMIN_TRANSFER_PROPERTY: 'ADMIN_TRANSFER_PROPERTY',
  ADMIN_TRIGGER_ECONOMY: 'ADMIN_TRIGGER_ECONOMY',
  ADMIN_SKIP_TURN: 'ADMIN_SKIP_TURN',
} as const;

// =============================================================================
// ACTION INTERFACES
// =============================================================================

// Game Lifecycle
export interface InitializeGameAction {
  type: typeof ActionTypes.INITIALIZE_GAME;
  payload: {
    gameId: string;
    roomCode: string;
    hostId: string;
    config: GameConfig;
    seed: number;
  };
}

export interface StartGameAction {
  type: typeof ActionTypes.START_GAME;
  payload: {
    initiatorId: string;
  };
}

export interface PauseGameAction {
  type: typeof ActionTypes.PAUSE_GAME;
  payload: {
    reason?: string;
  };
}

export interface ResumeGameAction {
  type: typeof ActionTypes.RESUME_GAME;
  payload: Record<string, never>;
}

export interface EndGameAction {
  type: typeof ActionTypes.END_GAME;
  payload: {
    reason: 'winner' | 'timeout' | 'admin' | 'forfeit';
    winnerId?: string;
  };
}

// Lobby
export interface AddPlayerAction {
  type: typeof ActionTypes.ADD_PLAYER;
  payload: {
    playerId: string;
    name: string;
    token: TokenType;
    color: string;
    socketId?: string;
  };
}

export interface RemovePlayerAction {
  type: typeof ActionTypes.REMOVE_PLAYER;
  payload: {
    playerId: string;
  };
}

export interface AddBotAction {
  type: typeof ActionTypes.ADD_BOT;
  payload: {
    botId: string;
    name: string;
    token: TokenType;
    color: string;
    personality: BotPersonality;
    difficulty: Difficulty;
  };
}

// Turn Actions
export interface RollDiceAction {
  type: typeof ActionTypes.ROLL_DICE;
  payload: {
    playerId: string;
  };
}

export interface EndTurnAction {
  type: typeof ActionTypes.END_TURN;
  payload: {
    playerId: string;
  };
}

// Property Actions
export interface BuyPropertyAction {
  type: typeof ActionTypes.BUY_PROPERTY;
  payload: {
    playerId: string;
    propertyId: number;
  };
}

export interface DeclinePropertyAction {
  type: typeof ActionTypes.DECLINE_PROPERTY;
  payload: {
    playerId: string;
    propertyId: number;
  };
}

export interface BuildHouseAction {
  type: typeof ActionTypes.BUILD_HOUSE;
  payload: {
    playerId: string;
    propertyId: number;
  };
}

export interface SellHouseAction {
  type: typeof ActionTypes.SELL_HOUSE;
  payload: {
    playerId: string;
    propertyId: number;
  };
}

export interface MortgagePropertyAction {
  type: typeof ActionTypes.MORTGAGE_PROPERTY;
  payload: {
    playerId: string;
    propertyId: number;
  };
}

export interface UnmortgagePropertyAction {
  type: typeof ActionTypes.UNMORTGAGE_PROPERTY;
  payload: {
    playerId: string;
    propertyId: number;
  };
}

// Jail Actions
export interface PayJailFineAction {
  type: typeof ActionTypes.PAY_JAIL_FINE;
  payload: {
    playerId: string;
  };
}

export interface UseJailCardAction {
  type: typeof ActionTypes.USE_JAIL_CARD;
  payload: {
    playerId: string;
  };
}

export interface RollForDoublesAction {
  type: typeof ActionTypes.ROLL_FOR_DOUBLES;
  payload: {
    playerId: string;
  };
}

// Finance Actions
export interface TakeLoanAction {
  type: typeof ActionTypes.TAKE_LOAN;
  payload: {
    playerId: string;
    amount: number;
    termRounds: number;
    isFixedRate: boolean;
  };
}

export interface RepayLoanAction {
  type: typeof ActionTypes.REPAY_LOAN;
  payload: {
    playerId: string;
    loanId: string;
    amount: number;
  };
}

export interface CreateCDAction {
  type: typeof ActionTypes.CREATE_CD;
  payload: {
    playerId: string;
    amount: number;
    termRounds: number;
  };
}

export interface WithdrawCDAction {
  type: typeof ActionTypes.WITHDRAW_CD;
  payload: {
    playerId: string;
    cdId: string;
    early: boolean;
  };
}

export interface OpenHELOCAction {
  type: typeof ActionTypes.OPEN_HELOC;
  payload: {
    playerId: string;
    propertyId: number;
    creditLimit: number;
  };
}

// Trade Actions
export interface ProposeTradeAction {
  type: typeof ActionTypes.PROPOSE_TRADE;
  payload: {
    proposerId: string;
    recipientId: string;
    offer: TradeOffer;
    request: TradeOffer;
  };
}

export interface AcceptTradeAction {
  type: typeof ActionTypes.ACCEPT_TRADE;
  payload: {
    tradeId: string;
    playerId: string;
  };
}

export interface RejectTradeAction {
  type: typeof ActionTypes.REJECT_TRADE;
  payload: {
    tradeId: string;
    playerId: string;
  };
}

export interface CounterTradeAction {
  type: typeof ActionTypes.COUNTER_TRADE;
  payload: {
    tradeId: string;
    playerId: string;
    counterOffer: TradeOffer;
    counterRequest: TradeOffer;
  };
}

// Auction Actions
export interface StartAuctionAction {
  type: typeof ActionTypes.START_AUCTION;
  payload: {
    propertyId: number;
    startingBid: number;
  };
}

export interface PlaceBidAction {
  type: typeof ActionTypes.PLACE_BID;
  payload: {
    playerId: string;
    auctionId: string;
    amount: number;
  };
}

export interface PassAuctionAction {
  type: typeof ActionTypes.PASS_AUCTION;
  payload: {
    playerId: string;
    auctionId: string;
  };
}

// Card Actions
export interface DrawCardAction {
  type: typeof ActionTypes.DRAW_CARD;
  payload: {
    playerId: string;
    deck: 'chance' | 'community_chest';
  };
}

// System Actions
export interface MovePlayerAction {
  type: typeof ActionTypes.MOVE_PLAYER;
  payload: {
    playerId: string;
    spaces: number;
    newPosition: number;
    passedGo: boolean;
  };
}

export interface CollectRentAction {
  type: typeof ActionTypes.COLLECT_RENT;
  payload: {
    fromPlayerId: string;
    toPlayerId: string;
    propertyId: number;
    amount: number;
  };
}

export interface SendToJailAction {
  type: typeof ActionTypes.SEND_TO_JAIL;
  payload: {
    playerId: string;
    reason: 'three_doubles' | 'go_to_jail_space' | 'card';
  };
}

export interface BankruptPlayerAction {
  type: typeof ActionTypes.BANKRUPT_PLAYER;
  payload: {
    playerId: string;
    creditorId: string | null; // null = bank
  };
}

export interface EconomyTickAction {
  type: typeof ActionTypes.ECONOMY_TICK;
  payload: {
    newPhase?: string;
    inflationChange?: number;
  };
}

// Admin Actions
export interface AdminAdjustMoneyAction {
  type: typeof ActionTypes.ADMIN_ADJUST_MONEY;
  payload: {
    playerId: string;
    amount: number;
    reason: string;
  };
}

export interface AdminMovePlayerAction {
  type: typeof ActionTypes.ADMIN_MOVE_PLAYER;
  payload: {
    playerId: string;
    newPosition: number;
    collectGo: boolean;
  };
}

// =============================================================================
// UNION TYPE
// =============================================================================

export type GameAction =
  | InitializeGameAction
  | StartGameAction
  | PauseGameAction
  | ResumeGameAction
  | EndGameAction
  | AddPlayerAction
  | RemovePlayerAction
  | AddBotAction
  | RollDiceAction
  | EndTurnAction
  | BuyPropertyAction
  | DeclinePropertyAction
  | BuildHouseAction
  | SellHouseAction
  | MortgagePropertyAction
  | UnmortgagePropertyAction
  | PayJailFineAction
  | UseJailCardAction
  | RollForDoublesAction
  | TakeLoanAction
  | RepayLoanAction
  | CreateCDAction
  | WithdrawCDAction
  | OpenHELOCAction
  | ProposeTradeAction
  | AcceptTradeAction
  | RejectTradeAction
  | CounterTradeAction
  | StartAuctionAction
  | PlaceBidAction
  | PassAuctionAction
  | DrawCardAction
  | MovePlayerAction
  | CollectRentAction
  | SendToJailAction
  | BankruptPlayerAction
  | EconomyTickAction
  | AdminAdjustMoneyAction
  | AdminMovePlayerAction;
